### ISSUE TITLE
Update queries.py

### ISSUE THREAD

**Issue by earthquakesan** [fr0gs/mu-docker-event-query#1]
The code in logger was aligned with ontology today. queries.py needs to be updated.

https://github.com/big-data-europe/mu-swarm-logger-service/commit/93624cb9b7f83320ad92f1928d808865f991c9d5

**Comment by earthquakesan** [comment]
Ontology description is available [here](https://github.com/big-data-europe/mu-swarm-logger-service/blob/master/docs/docker-engine-events/events.owl)

**Comment by fr0gs** [comment]
Queries updated, I am closing the issue.
